export enum BraintreeTransactionStatus {
   AUTHORIZATION_EXPIRED = 'AUTHORIZATION_EXPIRED',
   AUTHORIZED = 'AUTHORIZED',
   AUTHORIZING = 'AUTHORIZING',
   FAILED = 'FAILED',
   GATEWAY_REJECTED = 'GATEWAY_REJECTED',
   PROCESSOR_DECLINED = 'PROCESSOR_DECLINED',
   SETTLED = 'SETTLED',
   SETTLEMENT_PENDING = 'SETTLEMENT_PENDING',
   SETTLING = 'SETTLING',
   SUBMITTED_FOR_SETTLEMENT = 'SUBMITTED_FOR_SETTLEMENT',
   VOIDED = 'VOIDED'
}
